
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false